### ISSUE TITLE
Tour not continuing after redirect

### ISSUE THREAD

**Issue by brandonhall** [sorich87/bootstrap-tour#363]
Hi There,

Thanks for the excellent plugin. Unfortunately, I'm dealing with an issue I can't solve. I've tried path `RegExp`, with and without a redirect function, Using the fully qualified URL as the path. I can get the redirect to happen fine but the next step doesn't show up.

It is a Backbone app and the views are being triggered. Here's the steps code:

````
    return [
      {
        orphan: true,
        backdrop: true,
        title: "Welcome",
        content: this.template('admin/welcome')
      },
      {
        orphan: true,
        path: '/test/tour#new/user',
        element: 'textarea',
        title: "Create Users",
        content: this.template('admin/create_users')
      },
````
What am I doing wrong? I've also tried the promise, stepped through the `bootstrap-tour.js` code all without any luck.

Thanks for the help.

**Comment by reubenbrown** [comment]
@brandonhall  Is `bootstrap-tour.js` being loaded on the page you are redirecting to?

**Comment by brandonhall** [comment]
@reubenbrown Yes, it's a single page app so `bootstrap-tour.js` is already available.

**Comment by reubenbrown** [comment]
@brandonhall Hmm well if the `'textarea'` element is on the same page as the first step then you shouldn't need to redirect at all. It would seem then that your tour cannot locate the `'textarea'` element. Maybe try selecting a more specific element, like the textarea's class or id if it has one and see in debug mode if the tour can find it.

**Comment by ncampuzano** [comment]
I have the same problem with redirect. I have a button in a page but the Tour is in another page. Redirect happen but the Tour doesn't start. (All steps have element with ID)

**Comment by parliament718** [comment]
+1 same issue. Has anyone found a fix for this?

**Comment by parliament718** [comment]
Ok I was correct about the above regarding tour not waiting for the async template to load before continuing.

I needed to get past this as soon as possible so I implemented a fix in my angular application. It also required changes to bootstrap-tour.js which you can see in my fork. If anyone wants to port the fix into the coffeescript source and make a pull go for it. Might also want to remove the angular promise and use a jquery one instead. 

Here's the modified bootstrap-tour.js: https://github.com/parliament718/bootstrap-tour/blob/master/build/js/bootstrap-tour.js

And here's how I handle it in my app code. 

```
 new Tour({
           redirect: function (step) {
                                    var deferred = $q.defer();

                                    if ($location.path() != step.path) {
                                        if (step.templatePath) {
                                            $http.get(step.templatePath, { cache: $templateCache })
                                                .finally(function () {
                                                    $location.path(step.path);
                                                    $timeout(function () {
                                                        deferred.resolve();
                                                    });
                                                });

                                            return deferred.promise;
                                        }
                                    } 

                                    deferred.resolve();
                                    return deferred.promise;
                                }
   });
```

**Comment by parliament718** [comment]
I ended up reverting my fix because I found it wasn't working very well and still needed an arbitrary delay to work consistantly. I then found a better way, at least in Angular. What I did instead was initialize the Tour from inside an Angular directive and then I used that directive mlutiples times on different pages from WITHIN the asyn loaded template.

As long as the directive is placed within the template itself that needs to be awaited, then the Tour will intiailize properly. Then inside the directive I set the ```steps``` property on the tour based on the current path.

In this way I no longer needed any promise code to wait for the template to load, since it will have already been loaded by the time Angular bootstraps the directive used inside.

```
<div id="async-loaded-template">
   
     <div tour-directive></div> 
</div>
```

I then handled navigation between pages manually using the callback functions like onNext, onShown etc.

**Comment by sorich87** [comment]
Since #418, one can set the path as a hash for SPAs.

**Comment by Amenel** [comment]
For whoever comes across this issue: see [my answer on Stack Overflow](http://stackoverflow.com/a/40437341/2749913). I've had the issue too and the support for hashes in the path didn't solve the issue.

The gist of the solution I've implemented is that there needs to be an event, something that will cause bootstrap-tour to continue the tour, for as a matter of fact, it does not continue. For now, I just issue (in an Angular-based SPA) a `$(window).resize()` call. For some reason I didn't figure out, that's enough to cause the tour to continue. In the near future, I'll create a directive to handle that call, in a cleaner manner.

HTH.
